"""empty message

Revision ID: 328cc480f939
Revises: b82521cd7db1
Create Date: 2022-08-03 20:04:47.056866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328cc480f939'
down_revision = 'b82521cd7db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=1000), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
