"""empty message

Revision ID: 399cedcbb5f9
Revises: c1bb1889abc2
Create Date: 2023-01-14 04:56:15.273698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399cedcbb5f9'
down_revision = 'c1bb1889abc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prompt_id', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
