"""empty message

Revision ID: 5b6f5e3a4047
Revises: 399cedcbb5f9
Create Date: 2023-01-24 21:53:41.114840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6f5e3a4047'
down_revision = '399cedcbb5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_set_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_set_category',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('eng_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('thai_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
