"""empty message

Revision ID: 6c1b995c5ed4
Revises: aff6f917ac03
Create Date: 2023-01-13 03:14:54.449384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1b995c5ed4'
down_revision = 'aff6f917ac03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_sub_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_category'], ['prompt_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prompt', sa.Column('prompt_sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prompt', 'prompt_sub_category', ['prompt_sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt', type_='foreignkey')
    op.drop_column('prompt', 'prompt_sub_category_id')
    op.drop_table('prompt_sub_category')
    op.drop_table('prompt_category')
    # ### end Alembic commands ###
