"""empty message

Revision ID: aff6f917ac03
Revises: 089e9dfb6183
Create Date: 2023-01-13 01:20:55.304979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff6f917ac03'
down_revision = '089e9dfb6183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prompt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    op.drop_table('user')
    op.drop_table('image')
    # ### end Alembic commands ###
