"""empty message

Revision ID: b0578f41d9e3
Revises: 7f059a6a5517
Create Date: 2023-01-28 04:52:38.094625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0578f41d9e3'
down_revision = '7f059a6a5517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_card',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=150), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_collection',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_file_type',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_set',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_card_id'], ['model_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_card_model_collection',
    sa.Column('model_card_id', sa.Integer(), nullable=True),
    sa.Column('model_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_card_id'], ['model_card.id'], ),
    sa.ForeignKeyConstraint(['model_collection_id'], ['model_collection.id'], )
    )
    op.create_table('model_card_model_file_type',
    sa.Column('model_card_id', sa.Integer(), nullable=True),
    sa.Column('model_file_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_card_id'], ['model_card.id'], ),
    sa.ForeignKeyConstraint(['model_file_type_id'], ['model_file_type.id'], )
    )
    op.create_table('prompt_set_prompt',
    sa.Column('prompt_set_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_set.id'], )
    )
    op.create_table('prompt_set_prompt_category',
    sa.Column('prompt_set_id', sa.Integer(), nullable=True),
    sa.Column('prompt_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_category_id'], ['prompt_category.id'], ),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_set.id'], )
    )
    op.create_table('prompt_sub_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_category_id'], ['prompt_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_detail_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_sub_category_id'], ['prompt_sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_detail_category_prompt',
    sa.Column('prompt_detail_category_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_detail_category_id'], ['prompt_detail_category.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_detail_category_prompt')
    op.drop_table('prompt_detail_category')
    op.drop_table('prompt_sub_category')
    op.drop_table('prompt_set_prompt_category')
    op.drop_table('prompt_set_prompt')
    op.drop_table('model_card_model_file_type')
    op.drop_table('model_card_model_collection')
    op.drop_table('image')
    op.drop_table('user')
    op.drop_table('prompt_set')
    op.drop_table('prompt_category')
    op.drop_table('prompt')
    op.drop_table('model_file_type')
    op.drop_table('model_collection')
    op.drop_table('model_card')
    # ### end Alembic commands ###
