"""empty message

Revision ID: b82521cd7db1
Revises: 3b1f51de1a95
Create Date: 2022-08-03 20:04:21.450441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82521cd7db1'
down_revision = '3b1f51de1a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=1000), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
