"""empty message

Revision ID: c1bb1889abc2
Revises: 937717059241
Create Date: 2023-01-14 04:35:08.135122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bb1889abc2'
down_revision = '937717059241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prompt_sub_category',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_category_id'], ['prompt_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('thai_name', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('prompt_sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_sub_category_id'], ['prompt_sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('prompt_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('prompt')
    op.drop_table('prompt_sub_category')
    op.drop_table('user')
    op.drop_table('prompt_category')
    # ### end Alembic commands ###
